<?php

// MAINTENANT LE NAVIGATEUR PEUT DEMANDER N'IMPORTE QUOI
// LE NAVIAGTEUR CROIT DEMANDER DES FICHIERS OU DES DOSSIERS
// MAIS EN FAIT C'EST MON CODE PHP QUI RENVOIE LA REPONSE QU'ON VEUT
echo "MAPAGE";

// AVEC PHP JE PEUX SAVOIR CE QUE LE NAVIGATEUR A DEMANDE COMME URI
$uri = $_SERVER["REQUEST_URI"];

echo "<h1>LE NAVIGATEUR A DEMANDE CETTE URI: $uri</h1>";